name: midi_win_plugin
description: A new Flutter plugin project.
version: 0.0.1

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: MidiWinPluginCApi
